# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rugprint',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/rugprint',
                'lib_path': 'rugprint'},
  'syms': {'rugprint.core': {'rugprint.core.foo': ('core.html#foo', 'rugprint/core.py')}}}
